language: python
sudo: required
dist: xenial
python: "3.7"

install:
  - pip install cwltool

# We need to cd into tests in order for coverage to work
# (it searches for .coverage in the cwd)
script:
  - cwltool --validate gatk-best-practice-generic-germline-short-variant-per-sample-cal_decomposed.cwl
